---
"num_mfc": 8
"read_interval": 1
"mfc_layout_image": "mfc_layout.png"
mfc1:
  "name": "MFC 1"
  "flow_set": "TDAC0"
  "flow_read": "AIN0"
  "scale": 10000
  "offset": 0
  "setpoint": 0
mfc2:
  "name": "MFC 2"
  "flow_set": "TDAC1"
  "flow_read": "AIN1"
  "scale": 10000
  "offset": 0
  "setpoint": 0
mfc3:
  "name": "MFC 3"
  "flow_set": "TDAC2"
  "flow_read": "AIN2"
  "scale": 10000
  "offset": 0
  "setpoint": 0
mfc4:
  "name": "MFC 4"
  "flow_set": "TDAC3"
  "flow_read": "AIN3"
  "scale": 10000
  "offset": 0
  "setpoint": 0
mfc5:
  "name": "MFC 5"
  "flow_set": "TDAC4"
  "flow_read": "AIN4"
  "scale": 10000
  "offset": 0
  "setpoint": 0
mfc6:
  "name": "MFC 6"
  "flow_set": "TDAC5"
  "flow_read": "AIN5"
  "scale": 10000
  "offset": 0
  "setpoint": 0
mfc7:
  "name": "MFC 7"
  "flow_set": "TDAC6"
  "flow_read": "AIN6"
  "scale": 10000
  "offset": 0
  "setpoint": 0
mfc8:
  "name": "MFC 8"
  "flow_set": "TDAC7"
  "flow_read": "AIN7"
  "scale": 10000
  "offset": 0
  "setpoint": 0
