num_mfc: 8
read_interval: 1
mfc_layout_image: mfc_layout.png
mfc1:
  flow_read: AIN0
  flow_set: TDAC0
  name: MFC 1
  offset: 0
  scale: 10000
  setpoint: 0
mfc2:
  flow_read: AIN1
  flow_set: TDAC1
  name: MFC 2
  offset: 0
  scale: 10000
  setpoint: 0
mfc3:
  flow_read: AIN2
  flow_set: TDAC2
  name: MFC 3
  offset: 0
  scale: 10000
  setpoint: 0
mfc4:
  flow_read: AIN3
  flow_set: TDAC3
  name: MFC 4
  offset: 0
  scale: 10000
  setpoint: 0
mfc5:
  flow_read: AIN4
  flow_set: TDAC4
  name: MFC 5
  offset: 0
  scale: 10000
  setpoint: 0
mfc6:
  flow_read: AIN5
  flow_set: TDAC5
  name: MFC 6
  offset: 0
  scale: 10000
  setpoint: 0
mfc7:
  flow_read: AIN6
  flow_set: TDAC6
  name: MFC 7
  offset: 0
  scale: 10000
  setpoint: 0
mfc8:
  flow_read: AIN7
  flow_set: TDAC7
  name: MFC 8
  offset: 0
  scale: 10000
  setpoint: 0
